// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"getting-started.mdx": () => import("../content/docs/getting-started.mdx?collection=docs"), "index.mdx": () => import("../content/docs/index.mdx?collection=docs"), "self-hosting.mdx": () => import("../content/docs/self-hosting.mdx?collection=docs"), "architecture/index.mdx": () => import("../content/docs/architecture/index.mdx?collection=docs"), "architecture/mastra.mdx": () => import("../content/docs/architecture/mastra.mdx?collection=docs"), "architecture/streaming.mdx": () => import("../content/docs/architecture/streaming.mdx?collection=docs"), "architecture/zapier-sdk.mdx": () => import("../content/docs/architecture/zapier-sdk.mdx?collection=docs"), "core-concepts/approvals.mdx": () => import("../content/docs/core-concepts/approvals.mdx?collection=docs"), "core-concepts/guardrails.mdx": () => import("../content/docs/core-concepts/guardrails.mdx?collection=docs"), "core-concepts/index.mdx": () => import("../content/docs/core-concepts/index.mdx?collection=docs"), "core-concepts/memory.mdx": () => import("../content/docs/core-concepts/memory.mdx?collection=docs"), "core-concepts/tool-discovery.mdx": () => import("../content/docs/core-concepts/tool-discovery.mdx?collection=docs"), "core-concepts/voice.mdx": () => import("../content/docs/core-concepts/voice.mdx?collection=docs"), "core-concepts/workflows.mdx": () => import("../content/docs/core-concepts/workflows.mdx?collection=docs"), "channels/discord.mdx": () => import("../content/docs/channels/discord.mdx?collection=docs"), "channels/github.mdx": () => import("../content/docs/channels/github.mdx?collection=docs"), "channels/google-chat.mdx": () => import("../content/docs/channels/google-chat.mdx?collection=docs"), "channels/index.mdx": () => import("../content/docs/channels/index.mdx?collection=docs"), "channels/linear.mdx": () => import("../content/docs/channels/linear.mdx?collection=docs"), "channels/slack.mdx": () => import("../content/docs/channels/slack.mdx?collection=docs"), "channels/telegram.mdx": () => import("../content/docs/channels/telegram.mdx?collection=docs"), "integrations/a2a-cloud.mdx": () => import("../content/docs/integrations/a2a-cloud.mdx?collection=docs"), "integrations/a2a-self-hosted.mdx": () => import("../content/docs/integrations/a2a-self-hosted.mdx?collection=docs"), "integrations/index.mdx": () => import("../content/docs/integrations/index.mdx?collection=docs"), "integrations/mcp-cloud.mdx": () => import("../content/docs/integrations/mcp-cloud.mdx?collection=docs"), "integrations/mcp-self-hosted.mdx": () => import("../content/docs/integrations/mcp-self-hosted.mdx?collection=docs"), }),
};
export default browserCollections;