/**
 * Plain-English scale summary for an action awaiting approval (foreman-nz8b).
 *
 * Every write/destructive Zapier tool already prompts for approval — that part
 * was never missing. What was missing is that the prompt showed the request as
 * raw JSON, so a call writing 500 rows and a call writing one row look
 * identical at a glance: you scroll a wall of objects and click Approve. This
 * derives the one fact that wall hides — how many things the action touches —
 * so it can be stated above the JSON in a single sentence.
 *
 * This is deliberately NOT a second confirmation step. The approval gate stays
 * one click; the size just stops being something you have to count yourself.
 *
 * Pure and synchronous: it reads the same tool input the prompt already
 * displays. Tool ids are the kebab-case SDK method names generated by
 * `agents/src/lib/zapier-sdk-tools.ts`, and the parameter names below are read
 * from the SDK's own Zod schemas (`table`/`records`/`fields`/`inputs`), not
 * guessed — see rules/zapier-sdk.md.
 */

export type ActionScope = {
  /** How many items the action touches. `null` for whole-target operations. */
  count: number | null;
  /** The finished sentence to show above the request body. */
  sentence: string;
};

/** Turn a Zapier app or table slug into something readable. */
function humanize(value: unknown): string | null {
  if (typeof value !== "string" || !value.trim()) return null;
  const raw = value.trim();
  // Table params accept an id as well as a name; an id is noise in a sentence.
  if (/^[0-9]+$/.test(raw)) return null;
  if (/^[0-9a-f]{8}-[0-9a-f]{4}-/i.test(raw)) return null;
  return raw
    .replace(/[-_]+/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase())
    .trim();
}

function pluralize(count: number, noun: string): string {
  return `${count.toLocaleString()} ${noun}${count === 1 ? "" : "s"}`;
}

function arrayLength(value: unknown): number | null {
  return Array.isArray(value) ? value.length : null;
}

/**
 * `runAction`/`createActionRun` take an opaque `inputs` bag whose shape is the
 * chosen Zapier action's, not ours — so the only honest way to find a bulk
 * payload is to look for the largest collection inside it.
 */
function largestCollection(inputs: unknown): number | null {
  if (!inputs || typeof inputs !== "object") return null;
  let largest = 0;
  for (const value of Object.values(inputs as Record<string, unknown>)) {
    const length = arrayLength(value);
    if (length !== null && length > largest) largest = length;
  }
  return largest > 0 ? largest : null;
}

/** The table the action targets, phrased for the end of a sentence. */
function tablePhrase(input: Record<string, unknown>): string {
  const name = humanize(input.table);
  return name ? `the ${name} table` : "the table";
}

/**
 * Describe what an action is about to do, or `null` when there is nothing
 * worth saying — a single-item write is already legible as JSON, and adding a
 * sentence to every prompt would train people to skip the sentence.
 */
export function describeActionScope(toolName: string, rawInput: unknown): ActionScope | null {
  const input = (rawInput ?? {}) as Record<string, unknown>;

  switch (toolName) {
    case "create-table-records": {
      const count = arrayLength(input.records);
      if (count === null || count < 2) return null;
      return {
        count,
        sentence: `This will create ${pluralize(count, "record")} in ${tablePhrase(input)}.`,
      };
    }
    case "update-table-records": {
      const count = arrayLength(input.records);
      if (count === null || count < 2) return null;
      return {
        count,
        sentence: `This will overwrite ${pluralize(count, "record")} in ${tablePhrase(input)}.`,
      };
    }
    case "delete-table-records": {
      const count = arrayLength(input.records);
      if (count === null || count < 2) return null;
      return {
        count,
        sentence: `This will permanently delete ${pluralize(count, "record")} from ${tablePhrase(input)}.`,
      };
    }
    case "create-table-fields": {
      const count = arrayLength(input.fields);
      if (count === null || count < 2) return null;
      return {
        count,
        sentence: `This will add ${pluralize(count, "column")} to ${tablePhrase(input)}.`,
      };
    }
    case "delete-table-fields": {
      const count = arrayLength(input.fields);
      if (count === null || count < 2) return null;
      return {
        count,
        sentence: `This will permanently delete ${pluralize(count, "column")} — and everything stored in ${count === 1 ? "it" : "them"} — from ${tablePhrase(input)}.`,
      };
    }
    // No count to give, but the blast radius is the whole table, which is
    // exactly the case where `{"table":"Leads"}` looks harmlessly small.
    case "delete-table":
      return {
        count: null,
        sentence: `This will permanently delete ${tablePhrase(input)} and every record in it.`,
      };
    case "run-action":
    case "create-action-run": {
      const count = largestCollection(input.inputs);
      if (count === null || count < 2) return null;
      const app = humanize(input.app);
      return {
        count,
        sentence: app
          ? `This will send ${pluralize(count, "item")} to ${app} in one action.`
          : `This will send ${pluralize(count, "item")} in one action.`,
      };
    }
    default:
      return null;
  }
}
