import { loader } from "fumadocs-core/source";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore -- generated by fumadocs-mdx at build time
import { docs } from "../../.source/server";

export const source = loader({
  baseUrl: "/docs",
  source: docs.toFumadocsSource(),
});
